name: icthub-auth

x-authentik-service: &authentik-service
  image: ghcr.io/goauthentik/server:2026.5.5
  restart: unless-stopped
  env_file:
    - path: /etc/icthub-auth/authentik.env
      required: true
  environment:
    AUTHENTIK_LOG_LEVEL: warning
  volumes:
    - /home/winbeau/services/authentik-data/data:/data
    - ./blueprints:/blueprints/icthub:ro
    - ./custom-templates:/templates:ro
    - ./media:/data/media/public/icthub:ro
  depends_on:
    postgresql:
      condition: service_healthy
  security_opt:
    - no-new-privileges:true
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "5"

services:
  postgresql:
    image: postgres:16.11-alpine
    restart: unless-stopped
    env_file:
      - path: /etc/icthub-auth/authentik.env
        required: true
    volumes:
      - /home/winbeau/services/authentik-data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 10
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"

  server:
    <<: *authentik-service
    command: server
    ports:
      - 127.0.0.1:9000:9000

  worker:
    <<: *authentik-service
    command: worker
